// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameState } from "./GameState";
import type { PlayerBundle } from "./PlayerBundle";
import type { ServerMessage } from "./index";

export type ClientSyncPacket = { game_state: GameState, global_messages: Array<ServerMessage>, entities: Array<PlayerBundle>, };
