// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameEntity } from "./GameEntity";
import type { GameEntityType } from "./GameEntityType";
import type { Position } from "./Position";

/**
 * Base bundle containing common components for all game entities
 */
export type GameEntityBundle = { entity: GameEntity, entity_type: GameEntityType, name: string, position: Position, };
