// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectionId } from "./ConnectionId";
import type { GameEntityBundle } from "./GameEntityBundle";
import type { IsOnline } from "./IsOnline";

/**
 * Player entity bundle
 */
export type PlayerBundle = { game_entity_bundle: GameEntityBundle, is_online: IsOnline, connection_id: ConnectionId, };
