// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageAuthorType } from "./MessageAuthorType";

export type ServerMessage = { author_type: MessageAuthorType, author_name: string | null, content: string, };
